
export const csi = [
        {
            id : 1,
            img: "/Images/CaseStudy/1.png",
            owner : "Lorem Ipsum is simply",
            location : "Lorem Ipsum is simply dummy",
            project : "Lorem Ipsum is simply",
            moduletype : "Lorem Ipsum is simply dummy", 
            title : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, ",
            info1 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ",
            info2 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type typesetting, remaining essentially unchanged. ",
            info3 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ",
            p1 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
            p2 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
            p3 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
            p4 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
        },
        {
            id : 2,
            img: "/Images/CaseStudy/2.png",
            owner : "Lorem Ipsum is simply",
            location : "Lorem Ipsum is simply dummy",
            project : "Lorem Ipsum is simply",
            moduletype : "Lorem Ipsum is simply dummy", 
            title : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, ",
            info1 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ",
            info2 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type typesetting, remaining essentially unchanged. ",
            info3 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ",
            p1 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
            p2 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
            p3 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
            p4 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
        },
        {
            id : 3,
            img: "/Images/CaseStudy/3.png",
            owner : "Lorem Ipsum is simply",
            location : "Lorem Ipsum is simply dummy",
            project : "Lorem Ipsum is simply",
            moduletype : "Lorem Ipsum is simply dummy", 
            title : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, ",
            info1 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ",
            info2 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type typesetting, remaining essentially unchanged. ",
            info3 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ",
            p1 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
            p2 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
            p3 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
            p4 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
        },
        {
            id : 4,
            img: "/Images/CaseStudy/4.png",
            owner : "Lorem Ipsum is simply",
            location : "Lorem Ipsum is simply dummy",
            project : "Lorem Ipsum is simply",
            moduletype : "Lorem Ipsum is simply dummy", 
            title : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, ",
            info1 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ",
            info2 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type typesetting, remaining essentially unchanged. ",
            info3 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ",
            p1 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
            p2 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
            p3 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
            p4 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
        },
        {
            id : 5,
            img: "/Images/CaseStudy/5.png",
            owner : "Lorem Ipsum is simply",
            location : "Lorem Ipsum is simply dummy",
            project : "Lorem Ipsum is simply",
            moduletype : "Lorem Ipsum is simply dummy", 
            title : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, ",
            info1 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ",
            info2 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type typesetting, remaining essentially unchanged. ",
            info3 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ",
            p1 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
            p2 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
            p3 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
            p4 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
        },
        {
            id : 6,
            img: "/Images/CaseStudy/6.png",
            owner : "Lorem Ipsum is simply",
            location : "Lorem Ipsum is simply dummy",
            project : "Lorem Ipsum is simply",
            moduletype : "Lorem Ipsum is simply dummy", 
            title : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, ",
            info1 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ",
            info2 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type typesetting, remaining essentially unchanged. ",
            info3 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ",
            p1 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
            p2 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
            p3 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
            p4 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
        },
        {
            id : 7,
            img: "/Images/CaseStudy/6.png",
            owner : "Lorem Ipsum is simply",
            location : "Lorem Ipsum is simply dummy",
            project : "Lorem Ipsum is simply",
            moduletype : "Lorem Ipsum is simply dummy", 
            title : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, ",
            info1 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ",
            info2 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type typesetting, remaining essentially unchanged. ",
            info3 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ",
            p1 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
            p2 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
            p3 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
            p4 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
        },
        {
            id : 8,
            img: "/Images/CaseStudy/5.png",
            owner : "Lorem Ipsum is simply",
            location : "Lorem Ipsum is simply dummy",
            project : "Lorem Ipsum is simply",
            moduletype : "Lorem Ipsum is simply dummy", 
            title : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, ",
            info1 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ",
            info2 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type typesetting, remaining essentially unchanged. ",
            info3 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ",
            p1 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
            p2 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
            p3 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
            p4 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
        },
        {
            id : 9,
            img: "/Images/CaseStudy/4.png",
            owner : "Lorem Ipsum is simply",
            location : "Lorem Ipsum is simply dummy",
            project : "Lorem Ipsum is simply",
            moduletype : "Lorem Ipsum is simply dummy", 
            title : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, ",
            info1 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ",
            info2 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type typesetting, remaining essentially unchanged. ",
            info3 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ",
            p1 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
            p2 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
            p3 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
            p4 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
        },
        {
            id : 10,
            img: "/Images/CaseStudy/3.png",
            owner : "Lorem Ipsum is simply",
            location : "Lorem Ipsum is simply dummy",
            project : "Lorem Ipsum is simply",
            moduletype : "Lorem Ipsum is simply dummy", 
            title : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, ",
            info1 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ",
            info2 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type typesetting, remaining essentially unchanged. ",
            info3 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ",
            p1 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
            p2 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
            p3 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
            p4 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
        },
        {
            id : 11,
            img: "/Images/CaseStudy/2.png",
            owner : "Lorem Ipsum is simply",
            location : "Lorem Ipsum is simply dummy",
            project : "Lorem Ipsum is simply",
            moduletype : "Lorem Ipsum is simply dummy", 
            title : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, ",
            info1 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ",
            info2 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type typesetting, remaining essentially unchanged. ",
            info3 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ",
            p1 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
            p2 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
            p3 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
            p4 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
        },
        {
            id : 12,
            img: "/Images/CaseStudy/1.png",
            owner : "Lorem Ipsum is simply",
            location : "Lorem Ipsum is simply dummy",
            project : "Lorem Ipsum is simply",
            moduletype : "Lorem Ipsum is simply dummy", 
            title : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, ",
            info1 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ",
            info2 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type typesetting, remaining essentially unchanged. ",
            info3 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ",
            p1 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
            p2 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
            p3 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
            p4 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
        },
    ]

  return (
    <div>
      
    </div>
  )

