
export const csi = [
        {
            id : 1,
            img: "/Images/CaseStudy/1.png",
            owner : "Owner - A",
            location : "Location",
            project : "Project",
            moduletype : "Module Type", 
            title : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, ",
            info1 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ",
            info2 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type typesetting, remaining essentially unchanged. ",
            info3 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ",
            p1 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
            p2 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
            p3 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
            p4 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
        },
        {
            id : 2,
            img: "/Images/CaseStudy/2.png",
            owner : "Owner - B",
            location : "Location",
            project : "Project",
            moduletype : "Module Type", 
            title : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, ",
            info1 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ",
            info2 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type typesetting, remaining essentially unchanged. ",
            info3 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ",
            p1 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
            p2 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
            p3 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
            p4 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
        },
        {
            id : 3,
            img: "/Images/CaseStudy/3.png",
            owner : "Owner - C",
            location : "Location",
            project : "Project",
            moduletype : "Module Type", 
            title : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, ",
            info1 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ",
            info2 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type typesetting, remaining essentially unchanged. ",
            info3 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ",
            p1 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
            p2 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
            p3 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
            p4 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
        },
        {
            id : 4,
            img: "/Images/CaseStudy/4.png",
            owner : "Owner - D",
            location : "Location",
            project : "Project",
            moduletype : "Module Type", 
            title : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, ",
            info1 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ",
            info2 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type typesetting, remaining essentially unchanged. ",
            info3 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ",
            p1 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
            p2 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
            p3 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
            p4 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
        },
        {
            id : 5,
            img: "/Images/CaseStudy/5.png",
            owner : "Owner - E",
            location : "Location",
            project : "Project",
            moduletype : "Module Type", 
            title : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, ",
            info1 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ",
            info2 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type typesetting, remaining essentially unchanged. ",
            info3 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ",
            p1 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
            p2 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
            p3 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
            p4 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
        },
        {
            id : 6,
            img: "/Images/CaseStudy/6.png",
            owner : "Owner - F",
            location : "Location",
            project : "Project",
            moduletype : "Module Type", 
            title : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, ",
            info1 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ",
            info2 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type typesetting, remaining essentially unchanged. ",
            info3 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ",
            p1 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
            p2 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
            p3 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
            p4 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
        },
        {
            id : 7,
            img: "/Images/CaseStudy/6.png",
            owner : "Owner - G",
            location : "Location",
            project : "Project",
            moduletype : "Module Type", 
            title : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, ",
            info1 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ",
            info2 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type typesetting, remaining essentially unchanged. ",
            info3 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ",
            p1 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
            p2 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
            p3 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
            p4 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
        },
        {
            id : 8,
            img: "/Images/CaseStudy/5.png",
            owner : "Owner - H",
            location : "Location",
            project : "Project",
            moduletype : "Module Type", 
            title : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, ",
            info1 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ",
            info2 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type typesetting, remaining essentially unchanged. ",
            info3 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ",
            p1 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
            p2 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
            p3 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
            p4 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
        },
        {
            id : 9,
            img: "/Images/CaseStudy/4.png",
            owner : "Owner - I",
            location : "Location",
            project : "Project",
            moduletype : "Module Type", 
            title : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, ",
            info1 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ",
            info2 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type typesetting, remaining essentially unchanged. ",
            info3 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ",
            p1 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
            p2 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
            p3 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
            p4 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
        },
        {
            id : 10,
            img: "/Images/CaseStudy/3.png",
            owner : "Owner - J",
            location : "Location",
            project : "Project",
            moduletype : "Module Type", 
            title : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, ",
            info1 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ",
            info2 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type typesetting, remaining essentially unchanged. ",
            info3 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ",
            p1 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
            p2 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
            p3 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
            p4 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
        },
        {
            id : 11,
            img: "/Images/CaseStudy/2.png",
            owner : "Owner - K",
            location : "Location",
            project : "Project",
            moduletype : "Module Type", 
            title : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, ",
            info1 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ",
            info2 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type typesetting, remaining essentially unchanged. ",
            info3 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ",
            p1 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
            p2 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
            p3 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
            p4 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
        },
        {
            id : 12,
            img: "/Images/CaseStudy/1.png",
            owner : "Owner - L",
            location : "Location",
            project : "Project",
            moduletype : "Module Type", 
            title : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, ",
            info1 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ",
            info2 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type typesetting, remaining essentially unchanged. ",
            info3 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ",
            p1 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
            p2 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
            p3 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
            p4 : "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
        },
    ]

